development:
  adapter: mysql2
  database: login
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  socket: /tmp/mysql.sock
  username: root
  password:

test:
  adapter: mysql2
  database: sample_project_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  socket: /tmp/mysql.sock
  username: root
  password:

production:
  adapter: mysql2
  database: sample_project_prod
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  socket: /tmp/mysql.sock
  username: root
  password:
